//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dis_deber2
{
    public partial class Carrito
    {
        protected global::System.Web.UI.WebControls.Panel pnlCarritoVacio;
        protected global::System.Web.UI.WebControls.Panel pnlCarrito;
        protected global::System.Web.UI.WebControls.GridView gvCarrito;
        protected global::System.Web.UI.WebControls.Label lblTotal;
        protected global::System.Web.UI.WebControls.Button btnConfirmar;
        protected global::System.Web.UI.WebControls.Panel pnlResumenCompra;
        protected global::System.Web.UI.WebControls.Label lblResumenCliente;
        protected global::System.Web.UI.WebControls.Label lblResumenFecha;
        protected global::System.Web.UI.WebControls.Label lblResumenCorreo;
        protected global::System.Web.UI.WebControls.GridView gvResumen;
        protected global::System.Web.UI.WebControls.Label lblResumenTotal;
    }
}
