//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dis_deber2
{
    public partial class Catalogo
    {
        protected global::System.Web.UI.WebControls.Label lblCarritoCount;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.TextBox txtBuscar;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategoria;
        protected global::System.Web.UI.WebControls.Button btnFiltrar;
        protected global::System.Web.UI.WebControls.CheckBox chkOrdenAlfabetico;
        protected global::System.Web.UI.WebControls.GridView gvProductos;
        protected global::System.Web.UI.WebControls.Panel pnlVisualizador;
        protected global::System.Web.UI.WebControls.LinkButton btnCerrarVisualizador;
        protected global::System.Web.UI.WebControls.Label lblModalProducto;
        protected global::System.Web.UI.WebControls.Panel pnlSinImagenesModal;
        protected global::System.Web.UI.WebControls.Panel pnlCarruselModal;
        protected global::System.Web.UI.WebControls.Repeater rptCarruselModal;
    }
}
