//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dis_deber2
{
    public partial class Rombito
    {
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.TextBox txtNumero;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNumero;
        protected global::System.Web.UI.WebControls.RangeValidator rvNumero;
        protected global::System.Web.UI.WebControls.Button btnGenerar;
        protected global::System.Web.UI.WebControls.Panel pnlResultado;
        protected global::System.Web.UI.WebControls.Label lblInfoRombo;
        protected global::System.Web.UI.WebControls.Literal litRombo;
        protected global::System.Web.UI.WebControls.GridView gvHistorial;
    }
}
